build: test
	go build cmd/webshopd/webshopd.go

test:
	go test github.com/fcortesgamez/go-mongodb-example/internal/...
	go test github.com/fcortesgamez/go-mongodb-example/cmd/...

sanitize:
	go fmt ./internal/...
	go vet ./internal/...
	go fmt ./cmd/...
	go vet ./internal/...

clean:
	rm -f webshopd
